<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AllJob.Application\AllJob.Application.csproj" />
    <ProjectReference Include="..\AllJob.Domain\AllJob.Domain.csproj" />
    <ProjectReference Include="..\AllJob.Persistence\AllJob.Persistence.csproj" />
  </ItemGroup>

</Project>
